config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admin_users
  resources :candidates

  resources :categories

  namespace :admin do
    resources :categories
    resources :elections
    resources :candidates
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  post 'votes', to: 'votes#create'
  get '/' => 'home#index'
  get '/election/:id', to: 'elections#show', as: :election
  get '/categories', to: 'categories#index', as: :all_categories

  get '/embed/election/:id', to: 'widget#show'
  get '/admin', to: 'admin/dashboard#index', as: :dashboard
end

app/models/election.rb
class Election < ActiveRecord::Base
  extend FriendlyId

  belongs_to :category
  has_many :vote_summary
  has_many :candidate_combinations
  friendly_id :slug_candidates, use: :slugged

  after_create :update_slug

  # TODO return true if the election is running
  def active?
    true
  end

  # TODO call this method to close an election
  # It will also clean the combinations table
  def self.close(election_id)
    CandidateCombination.delete_all(election_id: election_id)
  end

  def candidates
    @candidates ||= begin
      Rails.cache.fetch("candidates_for_election_#{id}") do
        category.candidates
      end
    end
  end

  def ranking
    @ranking ||= begin
      candidates.joins(:vote_summary)
        .order('vote_summaries.total_votes desc')
        .select('candidates.*, vote_summaries.total_votes')
    end
  end

  def total_votes
    @total_votes ||= ranking.reduce(0) { |sum, c| sum + c.total_votes }
  end

  def top(count)
    ranking.take(count)
  end

  def image_url
    candidates.try(:first).try(:image_url)
  end

  def combinations
    @combinations ||= begin
      Rails.cache.fetch("election_combinations_#{id}", expires_in: 24.hours) do
        candidate_combinations
      end
    end
  end

  private

  # If the slug exist, we include the id at the end of the url. This is
  # because the url of an election will be repeated over and over again.
  # The default behavior of the friendly_id is to insert a sha1 code into
  # the url. We have to update after creating because during the creation
  # the id is still not available
  def update_slug
    update_attributes(slug: nil)
    save!
  end

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end
end

app/controllers/admin/elections_controller.rb
class Admin::ElectionsController < Admin::AdminController
  before_action :set_election, only: [:show, :edit, :update, :destroy]
  before_action :set_elections, only: [:index, :show, :new, :edit, :update]
  before_action :set_categories, only: [:edit, :new]

  # GET /elections
  # GET /elections.json
  def index
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
  end

  # GET /elections/new
  def new
    @election = Election.new
  end

  # GET /elections/1/edit
  def edit
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(election_params)
    respond_to do |format|
      if @election.save
        format.html { redirect_to [:admin, @election], notice: 'Election was successfully created.' }
        format.json { render :show, status: :created, location: @election }
      else
        format.html { render :new }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elections/1
  # PATCH/PUT /elections/1.json
  def update
    respond_to do |format|
      if @election.update(election_params)
        format.html { redirect_to [:admin, @election], notice: 'Election was successfully updated.' }
        format.json { render :show, status: :ok, location: @election }
      else
        format.html { render :edit }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election.destroy
    respond_to do |format|
      format.html { redirect_to admin_elections_url, notice: 'Election was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_election
    @election = Election.friendly.find(params[:id])
  end

  def set_elections
    @elections = Election.order(:title)
  end

  def set_categories
    @categories = Category.order(:name).map {|c| [c.name, c.id]}
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def election_params
    params.require(:election).permit(:title, :start_date, :finish_date, :status, :category_id)
  end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  def show
    @election = Election.friendly.find(params[:id])
    @user_combinations = UserCombinations.new(session_key)
    @combination = CandidateCombination.random_combination(@election, UserCombinations.new(session_key).list)
  end
end

app/views/admin/elections/_form.html.erb
<%= form_for([:admin, @election]) do |f| %>
  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% @election.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Type the title of the election' %>
  </div>

  <div class="field form-group">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, options_for_select(@categories, selected: f.object.category_id), {}, { include_blank: true, 'data-select' => 1 } %>
  </div>

  <div class="field form-group">
    <%= f.label :Active? %>
    <%= f.check_box :status %>
  </div>

  <br />
  <hr />

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>

    <%= link_to admin_elections_path do %>
      <%= f.button type: 'button', class: 'btn btn-danger' do %>
        <i class='fa fa-mail-reply'></i> Go back
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/elections/_menu.html.erb
<%= content_for :admin_menus do %>
  <%= render partial: 'shared/admin_tabs', locals: { active: 'elections' } %>
<% end %>

app/views/admin/elections/edit.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <h1>Editing Election</h1>

  <%= render 'form' %>
</div>

app/views/admin/elections/index.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <%= render partial: 'shared/notice_growl' %>

  <h1>Listing Elections</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Active?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @elections.each do |election| %>
        <tr>
          <td style="padding:5px;"><%= election.title %></td>
          <td style="padding:5px;"><%= election.category.name %></td>
          <td style="padding:5px;"><%= election.status == '1' %></td>
          <td class='icon'>
            <%= link_to admin_election_path(election) do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </td>
          <td class='icon'>
            <%= link_to edit_admin_election_path(election) do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </td>
          <td class='icon'>
            <%= link_to admin_election_path(election), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />
  <p>
    <%= link_to new_admin_election_path, class: 'btn btn-success' do %>
      <i class='fa fa-plus'></i> New Election
    <% end %>
  </p>
</div>

app/views/admin/elections/new.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <h1>New Election</h1>

  <%= render 'form' %>
</div>

app/views/admin/elections/show.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <%= render partial: 'shared/notice_growl' %>

  <h1><%= @election.title %></h1>

  <p>
    <strong>Title:</strong>
    <%= @election.title %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @election.category.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @election.status %>
  </p>

  <%= link_to edit_admin_election_path(@election) do %>
    <%= button_tag type: 'button', class: 'btn btn-default btn-white' do %>
      <i class='fa fa-edit'></i> Edit
    <% end %>
  <% end %>

  <%= link_to admin_elections_path do %>
    <%= button_tag type: 'button', class: 'btn btn-default btn-white' do %>
      <i class='fa fa-mail-reply'></i> Go back
    <% end %>
  <% end %>
</div>