config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admin_users
  resources :candidates

  resources :categories

  namespace :admin do
    resources :categories
    resources :elections
    resources :candidates
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  post 'votes', to: 'votes#create'
  get '/' => 'home#index'
  get '/election/:id', to: 'elections#show', as: :election
  get '/categories', to: 'categories#index', as: :all_categories

  get '/embed/election/:id', to: 'widget#show'
  get '/admin', to: 'admin/dashboard#index', as: :dashboard
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :vote_summary

  attachment :modified_image

  scope :from_category, ->(category_id) {
    joins(:categories).where(categories: { id: category_id }) if category_id.to_i > 0
  }

  def category
    self.try(:categories).try(:first)
  end
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < Admin::AdminController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.from_category(params[:category_id]).all
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @current_category = params[:category_id]
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @category = @candidate.try(:categories).try(:first).try(:id)
    @creative_commons = CreativeCommons.licenses.map { |version, url| [version, version] }
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        set_candidate_categories
        CandidateCombination.recombine_candidates(category)

        format.html { redirect_to [:admin, @candidate], notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        set_candidate_categories

        format.html { redirect_to [:admin, @candidate], notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    category = @candidate.category
    @candidate.destroy
    CandidateCombination.recombine_candidates(category)

    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_candidate
    @candidate = Candidate.find(params[:id])
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @creative_commons = CreativeCommons.licenses.map { |version, url| [version, version] }
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def candidate_params
    params.require(:candidate).permit(:name, :status, :image_url, :image_original_title, :image_original_url, :image_author_name, :image_author_url, :image_license, :modified_image)
  end

  def set_candidate_categories
    if category = Category.find(params['category']['category_id'])
      @candidate.categories << category
    else
      @candidate.categories.delete_all
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    puts "teste"
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @category = @candidate.try(:categories).try(:first).try(:id)
    @creative_commons = CreativeCommons.licenses.map { |version, url| [version, version] }
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        if category = Category.find(params['category']['category_id'])
          @candidate.categories << category
        else
          @candidate.categories.delete_all
        end

        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        if category = Category.find(params['category']['category_id'])
          @candidate.categories << category
        else
          @candidate.categories.delete_all
        end

        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
      @categories = Category.all.map{ |c| [c.name, c.id] }
      @creative_commons = CreativeCommons.licenses.map { |version, url| [version, version] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :status, :image_url, :image_original_title, :image_original_url, :image_author_name, :image_author_url, :image_license, :modified_image)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/admin/candidates/_form.html.erb
<%= form_for([:admin, @candidate]) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , size: 150%>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= select(:category, :category_id, @categories, include_blank: "Select category...", selected: @candidate.category.try(:id)) %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, size: 150 %>
  </div>
  <div class="field">
    <%= f.label "Original image page (with all the descriptions and rights for the image)" %><br>
    <%= f.text_field :image_original_url, size: 150 %>
  </div>
  <div class="field">
    <%= f.label "Original image title" %><br>
    <%= f.text_field :image_original_title, size: 150 %>
  </div>
  <div class="field">
    <%= f.label "Image author" %><br>
    <%= f.text_field :image_author_name, size: 150 %>
  </div>
  <div class="field">
    <%= f.label "Image author page" %><br>
    <%= f.text_field :image_author_url, size: 150 %>
  </div>
  <div class="field">
    <%= f.label "License CC (Creative Commons)" %><br>
    <%= select(:candidate, :image_license, @creative_commons, include_blank: "Select license...", selected: @candidate.image_license) %>
  </div>
  <div class="field">
    <%= f.label "Modified image" %><br>
    <%= f.attachment_field :modified_image %>
  </div>

  <br />
  <hr />

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>

    <%= link_to admin_candidates_path do %>
      <%= f.button type: 'button', class: 'btn btn-danger' do %>
        <i class='fa fa-mail-reply'></i> Go back
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/candidates/_menu.html.erb
<%= content_for :admin_menus do %>
  <%= render partial: 'shared/admin_tabs', locals: { active: 'candidates' } %>
<% end %>

app/views/admin/candidates/edit.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <h1>Editing Candidate</h1>

  <%= render 'form' %>
</div>

app/views/admin/candidates/index.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <%= render partial: 'shared/notice_growl' %>

  <h1>Listing Candidates</h1>

  <%= form_for(admin_categories_path, method: 'get') do |f| %>
    <label>Filtro por categoria:</label>
    <%= select_tag 'category_id', options_for_select(@categories, @current_category),
          include_blank: 'Todas as categorias', class: 'form-control',
          id: 'category-filter', onchange: '$(form).submit()' %>
  <% end %>
  <br />
  <hr />

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Category</th>
        <th>Image url</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.name %></td>
          <td><%= candidate.status %></td>
          <td><%= candidate.category.try(:name) %></td>

          <td><%= image_tag(candidate.image_url, style: 'max-width: 150px; max-height: 200px') %></td>

          <td class='icon'>
            <%= link_to admin_candidate_path(candidate) do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </td>
          <td class='icon'>
            <%= link_to edit_admin_candidate_path(candidate) do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </td>
          <td class='icon'>
            <%= link_to admin_candidate_path(candidate), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />
  <p>
    <%= link_to new_admin_candidate_path, class: 'btn btn-success' do %>
      <i class='fa fa-plus'></i> New Candidate
    <% end %>
  </p>
</div>

app/views/admin/candidates/new.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <h1>New Candidate</h1>

  <%= render 'form' %>
</div>

app/views/admin/candidates/show.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <%= render partial: 'shared/notice_growl' %>

  <p>
    <strong>Name:</strong>
    <%= @candidate.name %>
  </p>

  <% if @candidate.image_url %>
    <p>
      <strong>Original Image:</strong>
      <img src="<%= @candidate.image_url %>"/>
    </p>
  <% end %>

  <p>
    <strong>Modified Image:</strong>
    <%= image_tag attachment_url(@candidate, :modified_image, format: "jpg") %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= @candidate.image_url %>
  </p>

  <p>
    <strong>Original image page:</strong>
    <%= @candidate.image_original_url %>
  </p>

  <p>
    <strong>Original image title:</strong>
    <%= @candidate.image_original_title %>
  </p>

  <p>
    <strong>Image Author:</strong>
    <%= @candidate.image_author_name %>
  </p>

  <p>
    <strong>Image Author Page:</strong>
    <%= @candidate.image_author_url %>
  </p>

  <p>
    <strong>License from Creative Commons (CC):</strong>
    <%= @candidate.image_license %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @candidate.category.try(:name) %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @candidate.status %>
  </p>

  <%= link_to edit_admin_candidate_path(@candidate) do %>
    <%= button_tag type: 'button', class: 'btn btn-default btn-white' do %>
      <i class='fa fa-edit'></i> Edit
    <% end %>
  <% end %>

  <%= link_to admin_candidates_path do %>
    <%= button_tag type: 'button', class: 'btn btn-default btn-white' do %>
      <i class='fa fa-mail-reply'></i> Go back
    <% end %>
  <% end %>
</div>