config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admin_users
  resources :candidates

  resources :categories

  namespace :admin do
    resources :categories
    resources :elections
    resources :candidates
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  post 'votes', to: 'votes#create'
  get '/' => 'home#index'
  get '/election/:id', to: 'elections#show', as: :election
  get '/categories', to: 'categories#index', as: :all_categories

  get '/embed/election/:id', to: 'widget#show'
  get '/admin', to: 'admin/dashboard#index', as: :dashboard
end

app/views/shared/_admin_tabs.html.erb
<%= active ||= 'dashboard' %>

<ul class="nav nav-tabs" id='admin-tabs'>
  <li role="presentation" <%= 'class=active' if active == 'dashboard' %>>
    <%= link_to dashboard_path do %>
      <i class='fa fa-area-chart'></i> Dashboard
    <% end %>
  </li>
  <li role="presentation" <%= 'class=active' if active == 'categories' %>>
    <%= link_to admin_categories_path do %>
      <i class='fa fa-folder'></i> Categories
    <% end %>
  </li>
  <li role="presentation" <%= 'class=active' if active == 'elections' %>>
    <%= link_to admin_elections_path do %>
      <i class='fa fa-sitemap'></i> Elections
    <% end %>
  </li>
  <li role="presentation" <%= 'class=active' if active == 'candidates' %>>
    <%= link_to admin_candidates_path do %>
      <i class='fa fa-group'></i> Candidates
    <% end %>
  </li>
</ul>

app/views/shared/_header_menu.html.erb
<ul class="nav navbar-nav navbar-right header_menu">
  <li>
    <%= link_to all_categories_path do %>
      <i class='fa fa-th'></i> Categorias
    <% end %>
  </li>

  <% if user_signed_in? %>
    <li>
      <a href="javascript:;">
        <% if current_user.image %>
          <%= image_tag current_user.image, class: 'user-image' %>
        <% end %>
        <%= current_user.exhibition_name %>
      </a>
    </li>
    <li role="separator" class="divider"></li>
    <li>
      <%= link_to destroy_user_session_path, :method => :delete, 'data-ga-event' => 'Header, Sair' do %>
        <i class='fa fa-plane'></i> Sair
      <% end %>
    </li>
  <% else %>
    <li>
      <%= link_to new_user_session_path, 'data-ga-event' => 'Header, Entrar' do %>
        <i class='fa fa-arrow-right'></i> Entrar
      <% end %>
    </li>
  <% end %>

  <% if admin_user_signed_in? %>
    <li>
      <%= link_to dashboard_path do %>
        <i class='fa fa-area-chart'></i> Dashboard
      <% end %>
    </li>
    <li>
      <%= link_to('Admin Logout', destroy_user_session_path, :method => :delete) %>
    </li>
  <% end %>
</ul>

app/views/shared/_notice_growl.html.erb
<%= content_for :javascripts do %>
  <script>
    $.bootstrapGrowl("<%= notice %>");
  </script>
<% end if notice.present?%>