config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admin_users
  resources :candidates

  resources :categories

  namespace :admin do
    resources :categories
    resources :elections
    resources :candidates
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  post 'votes', to: 'votes#create'
  get '/' => 'home#index'
  get '/election/:id', to: 'elections#show', as: :election
  get '/categories', to: 'categories#index', as: :all_categories

  get '/embed/election/:id', to: 'widget#show'
  get '/admin', to: 'admin/dashboard#index', as: :dashboard
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged

  validate :valid_parent, on: :update

  belongs_to :parent, class_name: "Category", foreign_key: "parent_id"
  has_many :children, class_name: "Category", foreign_key: "parent_id"
  has_and_belongs_to_many :candidates
  has_many :elections
  has_many :vote_summary

  scope :with_elections, ->{ joins(:elections) }

  def has_parent?
    @has_parent ||= !self.parent.nil?
  end

  def image_url
    self.try(:candidates).try(:first).try(:image_url)
  end

  def valid_parent
    if self.id == self.parent_id
      errors.add(:parent, "can't be itself")
    end
  end

  def active_elections
    elections.select{ |election| election.active? }
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:index, :show, :new, :edit, :update]

  # GET /categories
  # GET /categories.json
  def index
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def set_categories
    @categories = Category.order(:name)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :parent_id, :status)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end

  def index
    @categories = Category.with_elections.order(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Type the name of the category' %>
  </div>

  <div class="field form-group">
    <%= f.label :parent_id %><br>
    <%= f.select :parent_id, options_for_select(nested_categories(@categories), selected: f.object.parent_id), {}, { include_blank: true, 'data-select' => 1 } %>
  </div>

  <div class="field form-group">
    <%= f.label :Active? %>
    <%= f.check_box :status %>
  </div>

  <br />
  <hr />

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>

    <%= link_to admin_categories_path do %>
      <%= f.button type: 'button', class: 'btn btn-danger' do %>
        <i class='fa fa-mail-reply'></i> Go back
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/categories/_menu.html.erb
<%= content_for :admin_menus do %>
  <%= render partial: 'shared/admin_tabs', locals: { active: 'categories' } %>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <h1>Editing Category</h1>

  <%= render 'form' %>
</div>

app/views/admin/categories/index.html.erb
<%= render partial: 'menu' %>

<div class="container admin-container">
  <%= render partial: 'shared/notice_growl' %>

  <h1>Listing Categories</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Active?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td style="padding:5px;"><%= nested_category(category.id) %></td>
          <td style="padding:5px;"><%= category.status %></td>
          <td class='icon'>
            <%= link_to admin_category_path(category) do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </td>
          <td class='icon'>
            <%= link_to edit_admin_category_path(category) do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </td>
          <td class='icon'>
            <%= link_to admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />
  <p>
    <%= link_to new_admin_category_path, class: 'btn btn-success' do %>
      <i class='fa fa-plus'></i> New Category
    <% end %>
  </p>
</div>

app/views/admin/categories/new.html.erb
<div class="container admin-container">
  <h1>New Category</h1>

  <%= render 'form' %>
</div>

app/views/admin/categories/show.html.erb
<div class="container admin-container">
  <%= render partial: 'notice_growl' %>

  <h1><%= @category.name %></h1>

  <p>
    <strong>Name:</strong>
    <%= @category.name %>
  </p>

  <p>
    <strong>Parent:</strong>
    <%= @category.parent_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @category.status %>
  </p>

  <%= link_to edit_admin_category_path(@category) do %>
    <%= button_tag type: 'button', class: 'btn btn-default btn-white' do %>
      <i class='fa fa-edit'></i> Edit
    <% end %>
  <% end %>

  <%= link_to admin_categories_path do %>
    <%= button_tag type: 'button', class: 'btn btn-default btn-white' do %>
      <i class='fa fa-mail-reply'></i> Go back
    <% end %>
  <% end %>
</div>